/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;


/**
 *
 * @author my pc
 */
public class ManageMembers extends javax.swing.JFrame {

    /**
     * Creates new form ManageBooks
     */
    
    String memberName, memberContact;
    int memberId;
    DefaultTableModel model;
    
    
    
    public ManageMembers() {
        initComponents();
        setMemberDetailsToTable();
    }
    
    
    //book database to the jframe table
    public void setMemberDetailsToTable(){
                model =(DefaultTableModel) tbl_memberDetails.getModel();
                model.setRowCount(0);
        
        
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_senanayake", "root", "");
            String sql = "SELECT * FROM member_details";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String memberId = rs.getString("member_id");
                String memberName = rs.getString("member_name");
                String gender = rs.getString("member_gender");
                String memberContact = rs.getString("member_contact");

                Object[] obj = {memberId, memberName, gender, memberContact};

                model.addRow(obj);
            }

            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txt_member_contact = new javax.swing.JTextField();
        txt_member_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_memberDelete = new javax.swing.JButton();
        btn_memberAdd = new javax.swing.JButton();
        btn_memberUpdate = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        combo_gender = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_memberDetails = new javax.swing.JTable();
        txt_member_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("X");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 30, -1));

        jLabel11.setFont(new java.awt.Font("Felix Titling", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Library management system");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 650, -1));

        jLabel16.setFont(new java.awt.Font("Berlin Sans FB", 0, 55)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 51, 51));
        jLabel16.setText("<");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, -1));

        jPanel2.setBackground(new java.awt.Color(237, 246, 246));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setDisplayedMnemonic('a');
        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_member_contact.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jPanel3.add(txt_member_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 300, -1));

        txt_member_name.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jPanel3.add(txt_member_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 300, -1));

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel2.setText("Contact number");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel5.setText("Member name");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel7.setText("Gender");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        btn_memberDelete.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btn_memberDelete.setText("Delete");
        btn_memberDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_memberDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btn_memberDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 190, 130, 50));

        btn_memberAdd.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btn_memberAdd.setText("Add");
        btn_memberAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_memberAddActionPerformed(evt);
            }
        });
        jPanel3.add(btn_memberAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 130, 50));

        btn_memberUpdate.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btn_memberUpdate.setText("Update");
        btn_memberUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_memberUpdateActionPerformed(evt);
            }
        });
        jPanel3.add(btn_memberUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 110, 130, 50));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setText("Manage members");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button_images/student.png"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        combo_gender.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        combo_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        combo_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_genderActionPerformed(evt);
            }
        });
        jPanel3.add(combo_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 1020, 330));

        jPanel4.setBackground(new java.awt.Color(237, 246, 246));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_memberDetails.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl_memberDetails.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        tbl_memberDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Member ID", "Name", "Gender", "Contact  Number"
            }
        ));
        tbl_memberDetails.setFillsViewportHeight(true);
        tbl_memberDetails.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_memberDetails.setRowHeight(30);
        tbl_memberDetails.setShowGrid(true);
        tbl_memberDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_memberDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_memberDetails);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 980, 340));

        txt_member_id.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        txt_member_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_member_idActionPerformed(evt);
            }
        });
        jPanel4.add(txt_member_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 300, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1020, 380));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void btn_memberDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_memberDeleteActionPerformed
        
      memberId = Integer.parseInt(txt_member_id.getText());

        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_senanayake", "root", "");
            String sql = "DELETE FROM member_details WHERE member_id=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, memberId);

            int deletedRows = pst.executeUpdate();
            if (deletedRows > 0) {
                JOptionPane.showMessageDialog(this, "Member deleted successfully");
                
                
        txt_member_name.setText("");
        txt_member_contact.setText("");                
                
                
                setMemberDetailsToTable();
            } else {
                JOptionPane.showMessageDialog(this, "Error deleting member");
            }
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btn_memberDeleteActionPerformed

    private void btn_memberUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_memberUpdateActionPerformed
        
   
        memberId = Integer.parseInt(txt_member_id.getText());
        memberName = txt_member_name.getText();
        memberContact = txt_member_contact.getText();
        String gender = combo_gender.getSelectedItem().toString();

        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_senanayake", "root", "");
            String sql = "UPDATE member_details SET member_name=?, member_gender=?, member_contact=? WHERE member_id=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, memberName);
            pst.setString(2, gender);
            pst.setString(3, memberContact);
            pst.setInt(4, memberId);

            int updatedRows = pst.executeUpdate();
            if (updatedRows > 0) {
                JOptionPane.showMessageDialog(this, "Member updated successfully");
                setMemberDetailsToTable();
                
        txt_member_name.setText("");
        txt_member_contact.setText("");
                
                
            } else {
                JOptionPane.showMessageDialog(this, "Error updating member");
            }
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
        }

    }//GEN-LAST:event_btn_memberUpdateActionPerformed

    private void tbl_memberDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_memberDetailsMouseClicked
        int row = tbl_memberDetails.getSelectedRow();
        txt_member_id.setText(model.getValueAt(row, 0).toString());
        txt_member_name.setText(model.getValueAt(row, 1).toString());
        combo_gender.setSelectedItem(model.getValueAt(row, 2).toString());
        txt_member_contact.setText(model.getValueAt(row, 3).toString());
    }//GEN-LAST:event_tbl_memberDetailsMouseClicked

    private void btn_memberAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_memberAddActionPerformed
        
         
        
        memberName = txt_member_name.getText();
        memberContact = txt_member_contact.getText();
        String gender = combo_gender.getSelectedItem().toString();

        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_senanayake", "root", "");
            String sql = "INSERT INTO member_details (member_name, member_gender, member_contact) VALUES (?, ?, ?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, memberName);
            pst.setString(2, gender);
            pst.setString(3, memberContact);

            int addedRows = pst.executeUpdate();
            if (addedRows > 0) {
                JOptionPane.showMessageDialog(this, "Member added successfully");
                setMemberDetailsToTable();
                
        txt_member_name.setText("");
        txt_member_contact.setText("");

                
            } else {
                JOptionPane.showMessageDialog(this, "Error adding member");
            }
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
        }


        
        
    }//GEN-LAST:event_btn_memberAddActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        
        this.dispose();
        new HomePage().setVisible(true);
        
    }//GEN-LAST:event_jLabel16MouseClicked

    private void txt_member_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_member_idActionPerformed

        String memberId = txt_member_id.getText();

        if (memberId.isEmpty()) {
            return;
        }

        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_senanayake", "root", "");
            String sql = "SELECT * FROM member_details WHERE member_id = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, memberId);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {

                txt_member_name.setText(rs.getString("member_name"));
                combo_gender.setSelectedItem(rs.getString("member_gender"));
                txt_member_contact.setText(rs.getString("member_contact"));

                DefaultTableModel model = (DefaultTableModel) tbl_memberDetails.getModel();
                for (int i = 0; i < model.getRowCount(); i++) {
                    if (model.getValueAt(i, 0).toString().equals(memberId)) {
                        tbl_memberDetails.setRowSelectionInterval(i, i);
                        tbl_memberDetails.scrollRectToVisible(tbl_memberDetails.getCellRect(i, 0, true)); // Scroll to the selected row
                        break;
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "No member found with the given ID.", "Error", JOptionPane.ERROR_MESSAGE);
            }

            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
        }

    }//GEN-LAST:event_txt_member_idActionPerformed

    private void combo_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_genderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageMembers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageMembers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageMembers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageMembers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageMembers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_memberAdd;
    private javax.swing.JButton btn_memberDelete;
    private javax.swing.JButton btn_memberUpdate;
    private javax.swing.JComboBox<String> combo_gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_memberDetails;
    private javax.swing.JTextField txt_member_contact;
    private javax.swing.JTextField txt_member_id;
    private javax.swing.JTextField txt_member_name;
    // End of variables declaration//GEN-END:variables
}
